### ISSUE TITLE
ROS2 unable to control acquisition rate

### ISSUE THREAD

**Issue by sisaha9** [astuff/avt_vimba_camera#110]
I have tried both setting it in the VimbaViewer as well as using the feature/AcquisitonFrameRateAbs parameter. No matter what the frame rate gets set to the AcquisitionFrameRateLimit. Is there any other way to do this?

**Comment by icolwell-as** [comment]
Hi @sisaha9, if you are unable to set the framerate to what you desire using only vimba viewer and not the ROS driver, then the issue is likely something with the camera or your configuration of the camera, and is not related to the ROS driver.
Your best option is to reach out to AVT support directly:
https://www.alliedvision.com/en/about-us/contact-us/technical-support-repair-/-rma/

Once you figure out how to set the framerate using vimba viewer, the ROS driver configs are the same and use the same Vimba API.

Good luck!
