### ISSUE TITLE
Triggering avt-camera via GPS

### ISSUE THREAD

**Issue by yulan0215** [astuff/avt_vimba_camera#30]
Hi:
I had a ublox GPS and I would like to trigger my avt-camera via PPS for synchronization. But for the setup in the driver of avt-camera, I do not know how to achieve it. Could you please tell me how to do the setup to achieve this function? Thx!
I used ROS melodic.

**Comment by icolwell-as** [comment]
Hi @yulan0215, you didn't specify which model of camera you have, but in general: You should be able to trigger the camera using the hardware trigger cable. If you attach the PPS from the GPS to the hardware trigger input on the camera, then configure the camera correctly, you should be able to trigger an image capture based on PPS events (rising or falling edges).

If you are an AutonomouStuff customer and purchased this equipment from us, please reach out to our support:
https://autonomoustuff.com/support

Otherwise, your best option is to contact Allied Vision directly:
https://www.alliedvision.com/en/support/
