### ISSUE TITLE
Support for AVT-VIMBA_USB camera?

### ISSUE THREAD

**Issue by WANGMuyang** [astuff/avt_vimba_camera#98]
Could we use the driver for AVT USB cameras rather than GigE cameras?  
Our camera moel is Allied Vision Camera Alvium 1800U-1242C.
It works in vimba viewer of Linux.
But when I tried to use the ROS driver. It needs IP to find the camera.

![3c6427d3a4fc0a69b9594222ac2dc72](https://user-images.githubusercontent.com/13785648/178442553-23121403-a8c1-4ee8-a6fe-3efab4fdf65e.png)
![62b569191bf60385586cf1037635f4d](https://user-images.githubusercontent.com/13785648/178442518-c2f33ec9-f16b-4129-b4aa-57e29dcbf769.png)

**Comment by icolwell-as** [comment]
Hi @WANGMuyang, you can use the GUID instead of the IP, the launch files just happen to use IP as a default.
You can get the GUID from Vimba Viewer, see the README for details on Vimba Viewer.

Regarding AVT USB cameras in general, you probably want to see this thread:
https://github.com/astuff/avt_vimba_camera/issues/86
