### ISSUE TITLE
TL not loaded?

### ISSUE THREAD

**Issue by ytwei1995** [astuff/avt_vimba_camera#99]
Our camera moel is Allied Vision Camera Alvium 1800U-1242C.
The code can run normally in Ubuntu20.04. However, when I use it in Ubuntu16.04, and TL not loaded.
However, camera can also be connected to open with "Vimba Viewer" tool.
If it is not compatible to Ubuntu 16.04?
![1658291115552](https://user-images.githubusercontent.com/107379677/179896605-0ce8debc-d323-4c4f-a2a1-88dab8b8c131.png)

**Comment by icolwell-as** [comment]
Hi @ytwei1995, Ubuntu 16.04/ROS Kinetic is now EOL, so I'd suggest using Ubuntu 20.04/ROS Noetic if you can, or ROS2 if that's an option.

That being said, there is a version that was released on kinetic, you may have luck with it, instead of building the latest master from source:
https://index.ros.org/p/avt_vimba_camera/github-astuff-avt_vimba_camera/#kinetic

Sometimes the "TL not loaded." error appears for various reasons, here are some other examples of people receiving the same error:
https://github.com/astuff/avt_vimba_camera/issues?q=TL+not+loaded
